import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowDown, ArrowRight, ArrowUp, BadgeCheck, BookOpen, Bot, ChevronDown, CircleHelp, Clock3, GripVertical, HeartHandshake, Menu, Play, Plus, RotateCcw, Settings2, ShieldCheck, Sparkles, Trash2, X } from 'lucide-react'
import './App.css'
import { completeReview, executeWorkflow } from './engine'
import { blockFromKind, blockMeta, puzzles } from './puzzles'
import type { BlockKind, RunReport, WorkflowBlock } from './types'

const difficultyColor: Record<string, string> = { Beginner: '#197a67', Intermediate: '#9a6313', Advanced: '#a14d70' }
const readStorage = <T,>(key: string, fallback: T): T => { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback } catch { return fallback } }
const writable = (value: unknown): Record<string, WorkflowBlock[]> => value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, WorkflowBlock[]> : {}

function App() {
  const [activeId, setActiveId] = useState(() => localStorage.getItem('puzzle-active') || puzzles[0].id)
  const [workflows, setWorkflows] = useState<Record<string, WorkflowBlock[]>>(() => writable(readStorage('puzzle-workflows', {})))
  const [solved, setSolved] = useState<string[]>(() => readStorage('puzzle-solved', []))
  const [report, setReport] = useState<RunReport | null>(null)
  const [selectedBlock, setSelectedBlock] = useState<string | null>(null)
  const [drawerOpen, setDrawerOpen] = useState(false)
  const [running, setRunning] = useState(false)
  const [reviewOpen, setReviewOpen] = useState(false)
  const [helpOpen, setHelpOpen] = useState(false)
  const [reviewNote, setReviewNote] = useState('')
  const [toast, setToast] = useState('')
  const runTimer = useRef<number | null>(null)

  const puzzle = useMemo(() => puzzles.find((item) => item.id === activeId) ?? puzzles[0], [activeId])
  const blocks = workflows[puzzle.id] ?? puzzle.starter
  const selected = blocks.find((block) => block.id === selectedBlock)
  const traceByBlock = Object.fromEntries((report?.traces ?? []).map((item) => [item.blockId, item]))
  const completed = solved.includes(puzzle.id)
  const clearRun = () => { if (runTimer.current) window.clearTimeout(runTimer.current); runTimer.current = null; setRunning(false) }

  useEffect(() => () => { if (runTimer.current) window.clearTimeout(runTimer.current) }, [])
  useEffect(() => { localStorage.setItem('puzzle-active', activeId) }, [activeId])
  useEffect(() => { localStorage.setItem('puzzle-workflows', JSON.stringify(workflows)) }, [workflows])
  useEffect(() => { localStorage.setItem('puzzle-solved', JSON.stringify(solved)) }, [solved])
  useEffect(() => { if (!toast) return; const id = window.setTimeout(() => setToast(''), 2800); return () => window.clearTimeout(id) }, [toast])

  function choosePuzzle(id: string) { clearRun(); setActiveId(id); setReport(null); setSelectedBlock(null); setDrawerOpen(false); setReviewOpen(false) }
  function updateBlocks(next: WorkflowBlock[]) { clearRun(); setWorkflows((all) => ({ ...all, [puzzle.id]: next })); setReport(null) }
  function addBlock(kind: BlockKind) { updateBlocks([...blocks, blockFromKind(kind, blocks.length)]); setToast(`${blockMeta[kind].label} added to the path`) }
  function moveBlock(index: number, direction: number) { const next = [...blocks]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; updateBlocks(next) }
  function deleteBlock(id: string) { updateBlocks(blocks.filter((block) => block.id !== id)); if (selectedBlock === id) setSelectedBlock(null) }
  function restore() { updateBlocks(puzzle.starter); setSelectedBlock(null); setToast('Starter path restored') }
  function run() { clearRun(); setRunning(true); setReport(null); runTimer.current = window.setTimeout(() => { const next = executeWorkflow(puzzle, blocks); setReport(next); setRunning(false); runTimer.current = null; if (next.status === 'review') setReviewOpen(true) }, 550) }
  function review(action: 'approved' | 'edited' | 'rejected') { setReviewOpen(false); setReport((current) => { if (!current) return current; const next = completeReview(current, action, reviewNote); if (next.status === 'success') setSolved((items) => items.includes(puzzle.id) ? items : [...items, puzzle.id]); return next }); setReviewNote(''); setToast(`Review ${action}`) }
  function keyboardSelect(event: React.KeyboardEvent<HTMLElement>, id: string) { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setSelectedBlock(id) } }

  return <div className="app-shell">
    <aside className={`sidebar ${drawerOpen ? 'open' : ''}`} aria-label="Puzzle library" aria-hidden={!drawerOpen && undefined}>
      <div className="brand"><div className="brand-mark"><Sparkles size={20} /></div><span>puzzle<span>flow</span></span><button className="mobile-close" onClick={() => setDrawerOpen(false)} aria-label="Close library"><X size={19} /></button></div>
      <div className="lab-label"><span>LEARNING LAB</span><div /><span className="mock-badge"><Bot size={13} /> MOCK MODE</span></div>
      <div className="library-heading"><div><strong>Puzzle shelf</strong><p>8 little worlds to untangle</p></div><BookOpen size={19} /></div>
      <nav className="puzzle-list">{(['Beginner', 'Intermediate', 'Advanced'] as const).map((level) => <section key={level}><h3 style={{ color: difficultyColor[level] }}>{level}</h3>{puzzles.filter((item) => item.difficulty === level).map((item) => <button key={item.id} aria-current={item.id === puzzle.id ? 'page' : undefined} className={`puzzle-link ${item.id === puzzle.id ? 'active' : ''}`} onClick={() => choosePuzzle(item.id)}><span className="puzzle-emoji">{item.emoji}</span><span><b>{item.number}. {item.title}</b><small>{item.brief}</small></span>{item.id === puzzle.id && <span className="active-dot" />}</button>)}</section>)}</nav>
      <div className="sidebar-footer"><div className="progress-orb">{solved.length}/8</div><div><b>Today’s spark</b><small>{completed ? 'Puzzle solved!' : `${solved.length} puzzle${solved.length === 1 ? '' : 's'} solved`}</small></div></div>
    </aside>
    <main className="main">
      <header className="topbar"><button className="icon-button menu-button" onClick={() => setDrawerOpen(true)} aria-label="Open puzzle library" aria-expanded={drawerOpen}><Menu /></button><div className="crumb"><span>Learning lab</span><ChevronDown size={15} /><b>{puzzle.difficulty} / {puzzle.number}</b></div><div className="top-actions"><span className="mock-badge top-mock"><Bot size={13} /> Mock mode</span><button className="help-button" onClick={() => setHelpOpen(true)}><CircleHelp size={18} /> How it works</button></div></header>
      <section className="hero-card"><div className={`hero-illustration ${puzzle.color}`}><span>{puzzle.emoji}</span><i>✦</i><i>✧</i></div><div className="hero-copy"><div className="eyebrow"><span style={{ color: difficultyColor[puzzle.difficulty] }}>{puzzle.difficulty.toUpperCase()}</span><span className="dot-separator">•</span> {puzzle.number} of 8</div><h1>{puzzle.title}</h1><p>{puzzle.objective}</p><div className="goal-pill"><span>◎</span><b>Goal</b>{puzzle.goal}</div></div><button className="hint-card" onClick={() => setToast(puzzle.hint)}><span>✦ HINT</span><p>{puzzle.hint}</p><ArrowRight size={16} /></button></section>
      <section className="workspace"><aside className="palette"><div className="section-title"><span>BUILDING BLOCKS</span><CircleHelp size={16} /></div><p className="palette-intro">Click a piece to add it to your path.</p>{(Object.keys(blockMeta) as BlockKind[]).map((kind) => <button className={`palette-block ${kind}`} key={kind} onClick={() => addBlock(kind)}><span className="block-symbol">{blockMeta[kind].icon}</span><span><b>{blockMeta[kind].label}</b><small>{blockMeta[kind].description}</small></span><Plus size={15} /></button>)}<div className="palette-tip"><ShieldCheck size={18} /><p><b>Every run is safe.</b> All AI and tools are predictable mock simulations.</p></div></aside>
        <section className="canvas-wrap"><div className="canvas-header"><div><span className="section-title">YOUR WORKFLOW</span><p>Arrange steps in the order they should happen.</p></div><button className="restore-button" onClick={restore}><RotateCcw size={15} /> Reset path</button></div><div className="workflow-canvas">{blocks.map((block, index) => { const entry = traceByBlock[block.id]; return <div className="step-group" key={block.id}><article tabIndex={0} role="button" aria-label={`Configure step ${index + 1}: ${block.label}`} className={`workflow-block ${block.kind} ${selectedBlock === block.id ? 'selected' : ''} ${entry?.status ?? ''}`} onClick={() => setSelectedBlock(block.id)} onKeyDown={(event) => keyboardSelect(event, block.id)}><div className="step-number">{index + 1}</div><GripVertical className="drag" size={17} /><span className="block-symbol">{blockMeta[block.kind].icon}</span><div className="workflow-copy"><b>{block.label}</b><span>{block.detail}</span>{entry && <em className={`trace-status ${entry.status}`}>{entry.status === 'success' ? 'Passed' : entry.status === 'fallback' ? 'Recovered' : entry.status === 'retry' ? 'Retried' : entry.status === 'review' ? 'Needs review' : entry.status === 'stopped' ? 'Safe stop' : entry.status === 'failed' ? 'Found issue' : 'Blocked'}</em>}</div><div className="block-actions"><button aria-label="Move step up" disabled={index === 0} onClick={(event) => { event.stopPropagation(); moveBlock(index, -1) }}><ArrowUp size={14} /></button><button aria-label="Move step down" disabled={index === blocks.length - 1} onClick={(event) => { event.stopPropagation(); moveBlock(index, 1) }}><ArrowDown size={14} /></button><button aria-label="Delete step" onClick={(event) => { event.stopPropagation(); deleteBlock(block.id) }}><Trash2 size={14} /></button></div></article>{index < blocks.length - 1 && <div className="connector"><span /></div>}</div> })}<button className="add-step" onClick={() => addBlock('prompt')}><Plus size={16} /> Add another step</button></div><div className="run-bar"><div><span className="mock-badge"><Bot size={13} /> DETERMINISTIC MOCK RUN</span><p>Same puzzle + same path = same outcome.</p></div><button className="run-button" onClick={run} disabled={running}><Play size={17} fill="currentColor" /> {running ? 'Running path…' : 'Run my workflow'}</button></div></section>
      </section>
      {(report || selected) && <section className="lower-grid"><section className="trace-panel"><div className="panel-heading"><div><span className="section-title">EXECUTION TRACE</span><h2>{report ? report.message : 'Configure your selected step'}</h2></div>{report && <div className="trace-actions"><span className={`run-status ${report.status}`}>{report.status === 'success' ? <BadgeCheck size={16} /> : <Clock3 size={16} />}{report.status}</span>{report.status === 'review' && <button className="resume-review" onClick={() => setReviewOpen(true)}>Resume review</button>}</div>}</div>{selected && <div className="config-card"><Settings2 size={19} /><div><b>{selected.label}</b><p>Configuration</p></div><input value={selected.config} onChange={(event) => updateBlocks(blocks.map((item) => item.id === selected.id ? { ...item, config: event.target.value } : item))} aria-label="Step configuration" /><button onClick={() => setSelectedBlock(null)}>Done</button></div>}{report && <div className="trace-list">{report.traces.map((item) => <div className={`trace-row ${item.status}`} key={item.id}><span className="trace-pin" /><div><b>{item.name}</b><small>{item.timestamp} · {item.input}</small></div><p>{item.output}</p>{item.recovery && <em>{item.recovery}</em>}</div>)}</div>}</section><Reliability report={report} /></section>}
    </main>
    {drawerOpen && <button className="scrim" onClick={() => setDrawerOpen(false)} aria-label="Close sidebar" />}
    {reviewOpen && <ReviewModal note={reviewNote} setNote={setReviewNote} onClose={() => setReviewOpen(false)} onReview={review} />}
    {helpOpen && <HelpModal onClose={() => setHelpOpen(false)} />}
    {toast && <div className="toast" role="status" aria-live="polite"><Sparkles size={16} /> {toast}</div>}
  </div>
}

function Reliability({ report }: { report: RunReport | null }) { const safeStops = report?.traces.filter((item) => item.status === 'stopped').length ?? 0; const issues = report?.traces.filter((item) => item.status === 'failed').length ?? 0; return <aside className="reliability"><div className="section-title">RELIABILITY READOUT <HeartHandshake size={16} /></div><div className="score"><div className="score-ring" style={{ '--score': report?.score ?? 0 } as React.CSSProperties}><span>{report?.score ?? '—'}{report && <small>%</small>}</span></div><div><h2>{report ? (report.score > 80 ? 'Thoughtful path' : 'Needs a guardrail') : 'Ready to test'}</h2><p>{report ? `${report.safeguards} safeguard${report.safeguards === 1 ? '' : 's'} engaged` : 'Run the path to measure it.'}</p></div></div><div className="reliability-stats"><div><b>{report?.retries ?? 0}</b><span>retries</span></div><div><b>{issues}</b><span>issues found</span></div><div><b>{safeStops}</b><span>safe stops</span></div></div><p className="reliability-note"><ShieldCheck size={16} /> Puzzleflow rewards recovery and honesty, not just a green check.</p></aside> }
function ReviewModal({ note, setNote, onClose, onReview }: { note: string; setNote: (value: string) => void; onClose: () => void; onReview: (action: 'approved' | 'edited' | 'rejected') => void }) { return <div className="modal-layer" role="dialog" aria-modal="true" aria-labelledby="review-title"><div className="review-modal"><button className="modal-close" onClick={onClose} aria-label="Close review"><X /></button><div className="review-symbol">◉</div><span className="eyebrow">HUMAN HANDOFF</span><h2 id="review-title">Your eyes are needed</h2><p>The workflow recovered safely. Read the mock draft and choose the next move.</p><div className="draft-card"><b>Mock draft</b><p>“Thanks for your patience. I can offer the policy-backed next step and keep you posted.”</p></div><label>Optional edit note<textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="e.g. make the opening a touch warmer" /></label><div className="review-actions"><button className="reject" onClick={() => onReview('rejected')}>Reject safely</button><button className="edit" onClick={() => onReview('edited')}>Approve with edit</button><button className="approve" onClick={() => onReview('approved')}>Approve <BadgeCheck size={16} /></button></div></div></div> }
function HelpModal({ onClose }: { onClose: () => void }) { return <div className="modal-layer" role="dialog" aria-modal="true" aria-labelledby="help-title"><div className="review-modal help-modal"><button className="modal-close" onClick={onClose} aria-label="Close how it works"><X /></button><div className="review-symbol">✦</div><span className="eyebrow">HOW IT WORKS</span><h2 id="help-title">Build a trustworthy path</h2><ol><li>Add and reorder blocks into a sequence.</li><li>Run deterministic mock AI and tools.</li><li>Use a fallback to retry once, or a safe stop to avoid guessing.</li><li>Finish human-review steps with an explicit decision.</li></ol><button className="approve full-button" onClick={onClose}>Got it</button></div></div> }
export default App
