import type { BlockKind, Puzzle, WorkflowBlock } from './types'

export const blockMeta: Record<BlockKind, { label: string; icon: string; description: string }> = {
  input: { label: 'Input', icon: '↓', description: 'Capture a known request or data.' },
  retrieval: { label: 'Retrieval', icon: '⌕', description: 'Fetch grounded mock context.' },
  condition: { label: 'Condition', icon: '?', description: 'Branch on a deterministic check.' },
  transform: { label: 'Transform', icon: '≋', description: 'Reshape data safely.' },
  retry: { label: 'Retry', icon: '⟳', description: 'Retry a pending failure, bounded.' },
  output: { label: 'Output', icon: '↑', description: 'Present the final safe result.' },
  prompt: { label: 'AI prompt', icon: '✦', description: 'Ask the deterministic mock AI.' },
  tool: { label: 'Tool call', icon: '⌘', description: 'Run a safe mock tool.' },
  validate: { label: 'Validator', icon: '✓', description: 'Check format and grounding.' },
  fallback: { label: 'Fallback', icon: '↪', description: 'Recover with a safer route.' },
  review: { label: 'Human review', icon: '◉', description: 'Pause for a human decision.' },
  safeStop: { label: 'Safe stop', icon: '■', description: 'Stop rather than guess.' },
}
const b = (id: string, kind: BlockKind, label: string, detail: string, config = ''): WorkflowBlock => ({ id, kind, label, detail, config })
const io = (prefix: string, subject: string) => [b(`${prefix}-in`, 'input', 'Capture request', `Receive the ${subject} request.`, 'structured request')]
const out = (prefix: string, subject: string) => b(`${prefix}-out`, 'output', 'Share safe result', `Present the grounded ${subject} result.`, 'plain language')

export const puzzles: Puzzle[] = [
  { id: 'museum', number: 1, title: 'Museum Matchmaker', difficulty: 'Beginner', emoji: '🏛️', color: 'coral', brief: 'Pair a visitor question with one accurate exhibit card.', objective: 'Build a grounded answer that never invents artwork details.', goal: 'Answer with a cited exhibit and ask a clarifying question when needed.', hint: 'Search before you speak; validate the citation.', starter: [...io('m', 'exhibit'), b('p1', 'prompt', 'Understand visitor', 'Extract intent from the question.', 'Classify art period'), b('m-retrieve', 'retrieval', 'Retrieve exhibit cards', 'Fetch relevant collection records.', 'collection index'), b('t1', 'tool', 'Search collection', 'Look up museum exhibit cards.', 'collection.search'), b('v1', 'validate', 'Check citation', 'Require an exhibit ID in the answer.', 'citation required'), b('s1', 'safeStop', 'Safe stop', 'Ask for a clearer artwork clue.', 'unknown artwork'), out('m', 'exhibit')], failureRule: { blockId: 'v1', kind: 'validate', config: 'citation required', message: 'No verified exhibit ID found in response.' } },
  { id: 'recipe', number: 2, title: 'Pantry Rescue', difficulty: 'Beginner', emoji: '🥕', color: 'mint', brief: 'Turn a tiny pantry into a practical dinner.', objective: 'Create a recipe using only confirmed ingredients.', goal: 'Never smuggle in missing ingredients.', hint: 'A validator catches the phantom lemon.', starter: [...io('r', 'recipe'), b('p2', 'prompt', 'Draft dinner', 'Propose a recipe from the pantry.', '3 ingredients'), b('r-condition', 'condition', 'Ingredients complete?', 'Check the pantry allowlist.', 'allowlist'), b('v2', 'validate', 'Pantry check', 'Compare ingredients to the list.', 'allowlist'), b('f2', 'fallback', 'Simplify recipe', 'Offer a two-ingredient alternative.', 'minimal recipe'), out('r', 'recipe')], failureRule: { blockId: 'v2', kind: 'validate', config: 'allowlist', message: 'Draft used lemon, which is not in the pantry.' } },
  { id: 'trip', number: 3, title: 'Tiny Trip Planner', difficulty: 'Beginner', emoji: '🗺️', color: 'sky', brief: 'Plan a calm afternoon route without making up opening hours.', objective: 'Use known facts, then safely stop for unavailable details.', goal: 'A trustworthy three-stop mini itinerary.', hint: 'Tools can be unavailable. Recover gracefully.', starter: [...io('t', 'itinerary'), b('p3', 'prompt', 'Shape route', 'Summarize the traveler preferences.', 'walkable'), b('t3', 'tool', 'Check hours', 'Query mock city listings.', 'hours.lookup'), b('f3', 'fallback', 'Use evergreen picks', 'Choose public spaces with no booking.', 'park + plaza'), b('s3', 'safeStop', 'Ask before booking', 'Avoid inventing reservation slots.', 'missing hours'), out('t', 'itinerary')], failureRule: { blockId: 't3', kind: 'tool', config: 'hours.lookup', message: 'City listings tool is unavailable.' } },
  { id: 'support', number: 4, title: 'Kind Support Reply', difficulty: 'Intermediate', emoji: '💌', color: 'lavender', brief: 'Draft an empathetic reply to a delayed delivery.', objective: 'Offer only policy-backed remedies and get a human approval.', goal: 'A warm, accurate response ready to send.', hint: 'The policy lookup is deliberately flaky once.', starter: [...io('s', 'reply'), b('p4', 'prompt', 'Draft empathy', 'Write a kind first draft.', 'tone: warm'), b('t4', 'tool', 'Read policy', 'Look up refund thresholds.', 'policy.delivery'), b('f4', 'fallback', 'Offer supported options', 'Use the standard delay language.', 'delay script'), b('r4', 'review', 'Send for approval', 'Human confirms the promise.', 'policy sensitive'), out('s', 'reply')], failureRule: { blockId: 't4', kind: 'tool', config: 'policy.delivery', message: 'Policy service timed out on attempt 1.' } },
  { id: 'data', number: 5, title: 'Messy Data Detective', difficulty: 'Intermediate', emoji: '🔎', color: 'butter', brief: 'Summarize a quirky CSV while protecting private notes.', objective: 'Separate useful trends from sensitive fields.', goal: 'A clear trend summary with redactions.', hint: 'Validation should run after transformation.', starter: [...io('d', 'summary'), b('p5', 'tool', 'Load sample CSV', 'Open deterministic mock data.', 'sample.csv'), b('d-transform', 'transform', 'Aggregate trends', 'Keep counts and remove raw notes.', 'group by category'), b('p5a', 'prompt', 'Spot trend', 'Name a pattern from allowed columns.', 'aggregate only'), b('v5', 'validate', 'Privacy lint', 'Detect names and private notes.', 'PII scan'), b('f5', 'fallback', 'Redact and retry', 'Replace sensitive fields with counts.', 'redact notes'), out('d', 'summary')], failureRule: { blockId: 'v5', kind: 'validate', config: 'PII scan', message: 'Private note detected in draft summary.' } },
  { id: 'invoice', number: 6, title: 'Invoice Inspector', difficulty: 'Intermediate', emoji: '🧾', color: 'peach', brief: 'Check an invoice math puzzle before it reaches finance.', objective: 'Catch a total mismatch, retry calculation, and escalate only if needed.', goal: 'A balanced invoice or a concise escalation.', hint: 'Retries are useful when inputs are stable.', starter: [...io('i', 'invoice'), b('t6', 'tool', 'Read line items', 'Load the mock invoice.', 'invoice-204'), b('v6', 'validate', 'Reconcile total', 'Compare lines and total.', 'sum check'), b('i-retry', 'retry', 'Retry calculation', 'Repeat the stable line-item sum.', 'max: 2'), b('r6', 'review', 'Finance review', 'Approve the adjustment.', 'amount changed'), out('i', 'invoice')], failureRule: { blockId: 'v6', kind: 'validate', config: 'sum check', message: 'Line items total $84.00, invoice says $86.00.' } },
  { id: 'safety', number: 7, title: 'Safety Scout', difficulty: 'Advanced', emoji: '🧗', color: 'rose', brief: 'Give hiking advice while refusing to guess about current trail hazards.', objective: 'Use evidence, show uncertainty, and stop on stale data.', goal: 'A cautious plan with an obvious handoff.', hint: 'Safe stops are a strength, not a failure.', starter: [...io('h', 'hiking plan'), b('p7', 'prompt', 'Understand hike', 'Extract route and experience.', 'risk aware'), b('t7', 'tool', 'Trail bulletin', 'Fetch mock bulletin.', 'trail.status'), b('v7', 'validate', 'Freshness check', 'Require a recent timestamp.', 'under 24h'), b('s7', 'safeStop', 'Safety handoff', 'Tell them to call the ranger station.', 'stale bulletin'), out('h', 'hiking plan')], failureRule: { blockId: 'v7', kind: 'validate', config: 'under 24h', message: 'Trail bulletin is 31 hours old.' } },
  { id: 'launch', number: 8, title: 'Launch Note Librarian', difficulty: 'Advanced', emoji: '🚀', color: 'violet', brief: 'Create a release note from scattered team updates.', objective: 'Keep only verified changes and route ambiguity to a reviewer.', goal: 'An honest, polished launch note.', hint: 'Use a fallback before human review.', starter: [...io('l', 'launch note'), b('t8', 'tool', 'Gather updates', 'Load mock team snippets.', 'release snippets'), b('l-retrieve', 'retrieval', 'Retrieve source snippets', 'Match statements to source updates.', 'verified snippets'), b('p8', 'prompt', 'Write release note', 'Synthesize confirmed changes.', 'no promises'), b('v8', 'validate', 'Claim checker', 'Flag unsupported claims.', 'evidence required'), b('f8', 'fallback', 'Use verified-only note', 'Remove unverified claims.', 'confirmed only'), b('r8', 'review', 'Release review', 'A human owns the final call.', 'public copy'), out('l', 'launch note')], failureRule: { blockId: 'v8', kind: 'validate', config: 'evidence required', message: '“Instant setup” has no source update.' } },
]
export const blockFromKind = (kind: BlockKind, ordinal: number): WorkflowBlock => { const meta = blockMeta[kind]; return b(`${kind}-${Date.now()}-${ordinal}`, kind, meta.label, meta.description, kind === 'retry' ? 'max: 2' : '') }
